version: '3.7'
services:

  mongo-1:
    image: mongo
    command: --replSet rs0

  mongo-2:
    image: mongo
    command: --replSet rs0

  mongo-3:
    image: mongo
    command: --replSet rs0

  mongo-4:
    image: mongo
    command: --replSet rs0

  replica-set-initializer:
    build: ./mongors
    depends_on:
      - mongo-1
      - mongo-2
      - mongo-3
      - mongo-4

  redis:
    image: redis

  smartproxy:
    image: smart-proxy:1.0
    ports:
      - "9000:8080"
    depends_on:
      - redis

  microservice:
    image: microservice:1.0
    depends_on:
      - replica-set-initializer
      - smartproxy